app:
  name: GatorFish
  port: :8080

database:
  dsn: Alin:Alin114514@@tcp(3.93.59.122:3306)/GatorFish?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenCons: 114

redis:
  addr: localhost:6379
  DB: 0
  Password: ""